### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by ghost** [tmcdonnell87/OFX-Manager#1]
Hi,

I was wondering what license this is under? Apache, GPL, MIT?

**Comment by tmcdonnell87** [comment]
Updated the readme file to clarify that it is under the MIT license.

**Comment by tmcdonnell87** [comment]
By the way, if you are interested in forking, let me know. There are a few things that aren't done 100% or that probably could be done to make it better software, but that I haven't had time to address.
